;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Pools.Projectiles.Arrow",DevComment="")
+GameplayTagList=(Tag="ResourceAttributes.Player.Health",DevComment="")
+GameplayTagList=(Tag="Settings.Gamepad.DeadzoneL",DevComment="")
+GameplayTagList=(Tag="Settings.Gamepad.DeadzoneR",DevComment="")
+GameplayTagList=(Tag="Settings.Gamepad.InvertX",DevComment="")
+GameplayTagList=(Tag="Settings.Gamepad.InvertY",DevComment="")
+GameplayTagList=(Tag="Settings.Gamepad.Sens",DevComment="")
+GameplayTagList=(Tag="Settings.MouseKeyboard.Sens",DevComment="")
+GameplayTagList=(Tag="Settings.Presets.Cinematic",DevComment="")
+GameplayTagList=(Tag="Settings.Presets.Epic",DevComment="")
+GameplayTagList=(Tag="Settings.Presets.High",DevComment="")
+GameplayTagList=(Tag="Settings.Presets.Low",DevComment="")
+GameplayTagList=(Tag="Settings.Presets.Medium",DevComment="")
+GameplayTagList=(Tag="UI.Menu.Character",DevComment="")
+GameplayTagList=(Tag="UI.Menu.Pause",DevComment="")

