;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="UI.Menu.Inventory",NewTagName="UI.Menu.Character")
+GameplayTagRedirects=(OldTagName="ResourceAttributes.Player.Level",NewTagName="ResourceAttributes.Player.Souls")
+GameplayTagRedirects=(OldTagName="Settings.Gamepad.Deadzone",NewTagName="Settings.Gamepad.DeadzoneR")
+GameplayTagList=(Tag="ResourceAttributes.Player.Health",DevComment="")
+GameplayTagList=(Tag="Settings.Gamepad.DeadzoneL",DevComment="")
+GameplayTagList=(Tag="Settings.Gamepad.DeadzoneR",DevComment="")
+GameplayTagList=(Tag="Settings.Gamepad.InvertX",DevComment="")
+GameplayTagList=(Tag="Settings.Gamepad.InvertY",DevComment="")
+GameplayTagList=(Tag="Settings.Gamepad.Sens",DevComment="")
+GameplayTagList=(Tag="Settings.MouseKeyboard.Sens",DevComment="")
+GameplayTagList=(Tag="UI.Menu.Character",DevComment="")
+GameplayTagList=(Tag="UI.Menu.Pause",DevComment="")

